# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LAW
email: user.dk.ko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm just a student, speed learning a ton of languages and messing around with github.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://userdkko.github.com" # the base hostname & protocol for your site
github_username:  userdkko

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
